# Factorización LU
## Factorización Doolitle

A=LU, donde L tiene 1's en la diagonal

In [10]:
import numpy as np

def LU(c):
    a=np.array(c)
    m=np.eye(n)
    per=np.eye(n)
    for k in range(n-1):
        p=k+np.argmax(np.abs(a[k:,k]))
        if p != k:
            a[[p,k],:]=a[[k,p],:]
            per[[p,k],:]=per[[k,p],:]
        if np.abs(a[k,k])==0:
            print('La matriz es singular')
            break
        else:
            for i in range(k+1,n):
                m[i,k]=a[i,k]/a[k,k]
                a[i,k:]=a[i,k:]-m[i,k]*a[k,k:]
    return(m,a,per)

n=3
a = np.array([1 ,2 ,3, 4, 5,6,8,9,0],
             dtype='f').reshape((n,n))
(L,U,P)=LU(a)
print('L =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in L]))
print('U =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in U]))
print('P =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in P]))

L =
   1.000   0.000   0.000
   0.500   1.000   0.000
   0.125   0.571   1.000
U =
   8.000   9.000   0.000
   0.000   0.875   3.000
   0.000   0.000   4.286
P =
   0.000   0.000   1.000
   1.000   0.000   0.000
   0.000   1.000   0.000


## Factorización de Crout
Realice la factorización de Crout A=LU donde U tiene 1's en la diagonal.

## Factorización Cholesky
 A=LL^T

In [12]:
import numpy as np
def cholesky(c):
    a=np.array(c)
    l=np.zeros_like(a)
    l[0,0]=np.sqrt(a[0,0])
    l[1:,0]=a[1:,0]/l[0,0]
    for j in range(1,n-1):
        l[j,j]=np.sqrt(
                a[j,j]-np.sum(l[j,0:j]**2))
        for i in range(j+1,n):
            l[i,j]=(a[i,j]-l[i,0:j].dot(
                            l[j,0:j]))/l[j,j]
    l[-1,-1]=np.sqrt(a[-1,-1]-np.sum(
            l[-1,0:-1]**2))
    return(l)

n=3
a= np.array([2 ,0 ,0, 
             1, 4, 0,
             1, 3, 9],
             dtype='f').reshape((n,n))
a=a.dot(a.T)
print('a =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in a]))
l=cholesky(a)
print('l =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in l]))

a =
   4.000   2.000   2.000
   2.000  17.000  13.000
   2.000  13.000  91.000
l =
   2.000   0.000   0.000
   1.000   4.000   0.000
   1.000   3.000   9.000
