In [1]:
import numpy as np

def LU(c):
    a=np.array(c)
    m=np.eye(n)
    per=np.eye(n)
    for k in range(n-1):
        p=k+np.argmax(np.abs(a[k:,k]))
        if p != k:
            a[[p,k],:]=a[[k,p],:]
            per[[p,k],:]=per[[k,p],:]
        if np.abs(a[k,k])==0:
            print('La matriz es singular')
            break
        else:
            for i in range(k+1,n):
                m[i,k]=a[i,k]/a[k,k]
                a[i,k:]=a[i,k:]-m[i,k]*a[k,k:]
    return(m,a,per)

n=4
a = np.array([8,7,9,5,6,7,9,8,4,3,3,1,2,1,1,0],
             dtype='f').reshape((n,n))
(L,U,P)=LU(a)
print('FACTORIZACION DOOLITLE')
print('L =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in L]))
print('U =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in U]))
print('P =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in P]))
print('FACTORIZACION CROUT')
d=np.ones_like(np.diag(U))/np.diag(U)
L2 = L @ np.diag(np.diag(U))
U2 = np.diag(d) @ U
print('L =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in L2]))
print('U =\n'+'\n'.join([''.join(['{:8.3f}'.format(item) for item in row]) 
      for row in U2]))

FACTORIZACION DOOLITLE
L =
   1.000   0.000   0.000   0.000
   0.750   1.000   0.000   0.000
   0.500  -0.286   1.000   0.000
   0.250  -0.429   0.333   1.000
U =
   8.000   7.000   9.000   5.000
   0.000   1.750   2.250   4.250
   0.000   0.000  -0.857  -0.286
   0.000   0.000   0.000   0.667
P =
   1.000   0.000   0.000   0.000
   0.000   1.000   0.000   0.000
   0.000   0.000   1.000   0.000
   0.000   0.000   0.000   1.000
FACTORIZACION CROUT
L =
   8.000   0.000   0.000   0.000
   6.000   1.750   0.000   0.000
   4.000  -0.500  -0.857   0.000
   2.000  -0.750  -0.286   0.667
U =
   1.000   0.875   1.125   0.625
   0.000   1.000   1.286   2.429
   0.000   0.000   1.000   0.333
   0.000   0.000   0.000   1.000
