# Método Cholesky
## Algoritmo
![cholesky](alg_chol.png)

In [2]:
import numpy as np
n=3
a = np.array([4,-2,2,-2,2,-4,2,-4,11],
             dtype='f').reshape((n,n))

In [11]:
def chol(a):
    n = a.shape[0]
    l = np.zeros_like(a)
    l[0,0]=np.sqrt(a[0,0])
    for k in range(n-1):
        l[k+1,0]=a[k+1,0]/l[0,0]
        for i in range(1,k+1):
            l[k+1,i]=(a[k+1,i]-np.dot(l[i,0:i],l[k+1,0:i]))/l[i,i]
        l[k+1,k+1]=np.sqrt(a[k+1,k+1]-np.sum(l[k+1,0:k+1]**2))
    return l

In [14]:
l = chol(a)
print(l)

[[ 2.  0.  0.]
 [-1.  1.  0.]
 [ 1. -3.  1.]]


In [15]:
print(np.linalg.cholesky(a))

[[ 2.  0.  0.]
 [-1.  1.  0.]
 [ 1. -3.  1.]]


In [16]:
np.dot(l,l.T)

array([[ 4., -2.,  2.],
       [-2.,  2., -4.],
       [ 2., -4., 11.]], dtype=float32)

## Algoritmo de Gram–Schmidt clásico
![Gram–Schmidt clásico](alg_gs.png)

In [24]:
def gs(a):
    q=np.array(a)    
    (m,n) = a.shape
    r=np.zeros((n,n),dtype='f')    
    for j in range(n):
        v = a[:,j] 
        for i in range(j-1):
            r[i,j]   = q[:,i].dot(a[:,j])
            v = v - r[i,j]*q[:,i]
        r[j,j]=np.linalg.norm(v)
        q[:,j]=v/r[j,j]
    return(r,q)


a = np.array([2, 6, -19, 4, 2, 2, -2, -1, 4,1,3,-12],dtype='f').reshape(4,3)
(u,e) = gs(a)
# Comprobamos la factorizacion
print(e @ u) 

[[  2.   6. -19.]
 [  4.   2.   2.]
 [ -2.  -1.   4.]
 [  1.   3. -12.]]


## Algoritmo de Gram–Schmidt modificado.
![Gram–Schmidt modificado](alg_gs2.png)

In [26]:
def gs2(a):
    e=np.zeros_like(a)    
    m= a.shape[0]    
    n= a.shape[1]
    u=np.zeros((n,n),dtype='f')    
    for j in range(n):
        e[:,j] = a[:,j]
        for i in range(j-1):
            u[i,j]  = e[:,i].dot(e[:,j])
            e[:,j]  = e[:,j]-u[i,j]*e[:,i]
        u[j,j]=np.linalg.norm(e[:,j])
        e[:,j]=e[:,j]/u[j,j]
    return(u,e)

a = np.array([2, 6, -19, 4, 2, 2, -2, -1, 4,1,3,-12],dtype='f').reshape(4,3)
(u,e) = gs2(a)
# Comprobamos la factorizacion
print(e @ u)    

[[  2.   6. -19.]
 [  4.   2.   2.]
 [ -2.  -1.   4.]
 [  1.   3. -12.]]
